<h1 class="page-header text-center"><strong>HATA OLUŞTU</strong></h1>
<div class="alert alert-danger visible-lg">
    <div class="text-danger">
    <p>Hatanın bir kaç sebebi olabilir</p>
    <ol>
        <li>Olmayan bir sayfaya girmeye kalkıştınız.</li>
        <li>Yetkiniz olmayan bir işlem isteğinde bulundunuz.</li>
        <li>Bizim sistemimizde sorun var. Bu durumda gerekli denetimler yapılacaktır.</li>
    </ol>
    </div>
</div>