    <div class="form-ilanolustur clearfix">
    <h3 ng-bind="form_baslik" class="text-center"></h3>
    <form class="asagi_itekle" name="form_ilan" novalidate ng-submit="formu_gonder()">
        <div class="panel panel-default">
            <div class="panel-heading arka-baslik">
                <h4 class="panel-title">Genel Bilgiler</h4>
            </div>
            <div class="panel-body">
                <div class="row form-group">
                    <div class="col-lg-8 col-lg-push-2">
                        İlan Başlığı:
                        <input type="text" class="form-control"
                               name="baslik"
                               ng-minlength=10
                               ng-maxlength=100
                               ng-model="ilan.baslik"
                               required/>
                        <div class="alert alert-danger alert-dismissable" ng-show="form_ilan.baslik.$dirty && form_ilan.baslik.$invalid">
                            <span ng-bind="hataGoster({'tur':form_ilan.baslik.$error, 'uzunluk': {min:10, max:100}})"></span>
                        </div>
                    </div>
                </div>
                <div class="row form-group">
                    <div class="col-lg-8 col-lg-push-2">
                        Açıklama:
                        <textarea class="form-control"
                                  ng-maxlength=200
                                  name="aciklama"
                                  ng-model="ilan.aciklama"></textarea>
                        <div class="alert alert-danger alert-dismissable"
                             ng-show="form_ilan.aciklama.$dirty && form_ilan.aciklama.$invalid">
                            <span ng-bind="hataGoster({'tur':form_ilan.aciklama.$error, 'uzunluk': {max:200}})"></span>
                        </div>
                    </div>
                </div>
                <div class="row form-group">
                    <div class="col-lg-4 col-lg-push-2">
                        Gayrimenkul Türü:
                        <select class="form-control"
                                ng-model="ilan.gayrimenkul_turu"
                                required>
                            <option value="" selected>Seçiniz..</option>
                            <option value="1">Ev</option>
                            <option value="2">İşyeri</option>
                            <option value="3">Arazi</option>
                        </select>
                    </div>
                    <div class="col-lg-4 col-lg-push-2">
                        İlan Türü:
                        <select class="form-control"
                                ng-model="ilan.tur"
                                required>
                            <option value="" selected>Seçiniz..</option>
                            <option value="1">Kiralık</option>
                            <option value="2">Satılık</option>
                        </select>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">Medya (Fotoğraf, Kroki ...)</h4>
            </div>
            <div class="panel-body">
                <div class="row form-group">
                    <div class="col-lg-3 ">
                        <input type="button" class="btn btn-primary btn-lg" value="Dosyaları Seç.."/>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">Gayrimenkul Özellikleri</h4>
            </div>
            <div class="panel-body">
                <div class="row form-group">
                    <div class="col-lg-2 col-lg-push-3 form-control-static">
                        Oda türü:
                    </div>
                    <div class="col-lg-2 col-lg-push-3">
                        <input type="text" class="form-control"
                               ng-model="ilan.oda_turu"
                               required/>
                    </div>
                </div>
                <div class="row form-group">
                    <div class="col-lg-2 col-lg-push-3 form-control-static">
                        Metrekare:
                    </div>
                    <div class="col-lg-2 col-lg-push-3">
                        <input type="number"
                               class="form-control"
                               name="metrekare"
                               ng-model="ilan.metrekare"
                               min=1
                               max=100000
                               required/>
                        <div class="alert alert-danger alert-dismissable"
                             ng-show="form_ilan.metrekare.$dirty && form_ilan.metrekare.$invalid">
                            <span ng-bind="hataGoster({'tur':form_ilan.metrekare.$error, 'sinir': {min:1, max:100000}})"></span>
                        </div>
                    </div>
                </div>
                <div class="row form-group">
                    <div class="col-lg-2 col-lg-push-3 form-control-static">
                        Bulunduğu Kat:
                    </div>
                    <div class="col-lg-2 col-lg-push-3">
                        <input type="number"
                               class="form-control"
                               name="bulundugu_kat"
                               ng-model="ilan.bulundugu_kat"
                               required/>
                        <div class="alert alert-danger alert-dismissable"
                             ng-show="form_ilan.bulundugu_kat.$dirty && form_ilan.bulundugu_kat.$invalid">
                            <span ng-bind="hataGoster({'tur':form_ilan.bulundugu_kat.$error})"></span>
                        </div>
                    </div>
                </div>
                <div class="row form-group">
                    <div class="col-lg-2 col-lg-push-3 form-control-static">
                        Kaç Yıllık:
                    </div>
                    <div class="col-lg-2 col-lg-push-3">
                        <input type="number" class="form-control"
                               name="kac_yillik"
                               min=1
                               max=100
                               ng-model="ilan.kac_yillik"
                               required/>
                        <div class="alert alert-danger alert-dismissable"
                             ng-show="form_ilan.kac_yillik.$dirty && form_ilan.kac_yillik.$invalid">
                            <span ng-bind="hataGoster({'tur':form_ilan.kac_yillik.$error, 'sinir':{min:1, max:100}})"></span>
                        </div>
                    </div>
                </div>
                <div class="row form-group">
                    <div class="col-lg-2 col-lg-push-3 form-control-static">
                        İstenilen Fiyat:
                    </div>
                    <div class="col-lg-2 col-lg-push-3">
                        <input type="number" class="form-control"
                               ng-minlength=1
                               name="fiyat"
                               ng-model="ilan.istenilen_fiyat"
                               required/>
                        <div class="alert alert-danger alert-dismissable"
                             ng-show="form_ilan.fiyat.$dirty && form_ilan.fiyat.$invalid">
                            <span ng-bind="hataGoster({'tur':form_ilan.fiyat.$error})"></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel panel-default" ng-controller="GeoController">
            <div class="panel-heading">
                <h4 class="panel-title">Adres/İletişim Bilgileri</h4>
            </div>
            <div class="panel-body">
                <div class="row form-group">
                    <div class="col-lg-2 col-lg-push-2 form-control-static">
                        İl:
                    </div>
                    <div class="col-lg-4 col-lg-push-2">
                        <select class="form-control"
                                ng-model="ilan.il"
                                name="il"
                                required>
                            <option value="" selected>Seçiniz..</option>
                            <?php
                            	$geo = new Mysql("geo");
                            	 
	                            Mysql::sql($geo)
	                            ->select('id as kod,il as ad')
	                            ->from('iller')
	                            ->calistir();
	                            
	                            if ($geo->etkilenenSatirSayisi > 0)
	                            {
	                            	foreach ($geo->sonuc(true)->alMesaj() as $il)
	                            	{
	                            		echo '<option value="'.$il["kod"].'">'.$il["ad"].'</option>';
	                            	}	
	                            }
                            ?>
                        </select>
                        <div class="alert alert-danger alert-dismissable"
                             ng-show="form_ilan.il.$dirty && form_ilan.il.$invalid">
                            <span ng-bind="hataGoster({'tur':form_ilan.il.$error})"></span>
                        </div>
                    </div>
                </div>
                <div class="row form-group" ng-show="ilan.il > 0">
                    <div class="col-lg-2 col-lg-push-2 form-control-static">
                        İlçe:
                    </div>
                    <div class="col-lg-4 col-lg-push-2">
                        <select class="form-control"
                                ng-model="ilan.ilce"
                                name="ilce"
                                ng-options="ilce.kod as ilce.ad for ilce in ilceler"
                                required>
                            <option value="" selected>Seçiniz..</option>
                            <option value="">{{ilce.ad}}</option>
                        </select>
                        <div class="alert alert-danger alert-dismissable"
                             ng-show="form_ilan.ilce.$dirty && form_ilan.ilce.$invalid">
                            <span ng-bind="hataGoster({'tur':form_ilan.ilce.$error})"></span>
                        </div>
                    </div>
                </div>
                <div class="row form-group" ng-show="ilan.ilce > 0">
                    <div class="col-lg-2 col-lg-push-2 form-control-static">
                        Semt:
                    </div>
                    <div class="col-lg-4 col-lg-push-2">
                        <select class="form-control"
                                ng-model="ilan.semt"
                                name="semt"
                                ng-options="semt.kod as semt.ad for semt in semtler"
                                required>
                            <option value="" selected>Seçiniz..</option>
                            <option value="">{{semt.ad}}</option>
                        </select>
                        <div class="alert alert-danger alert-dismissable"
                             ng-show="form_ilan.semt.$dirty && form_ilan.semt.$invalid">
                            <span ng-bind="hataGoster({'tur':form_ilan.semt.$error})"></span>
                        </div>
                    </div>
                </div>
                <div class="row form-group" ng-show="ilan.semt > 0">
                    <div class="col-lg-2 col-lg-push-2 form-control-static">
                        Mahalle:
                    </div>
                    <div class="col-lg-4 col-lg-push-2">
                        <select class="form-control"
                                ng-model="ilan.mahalle"
                                name="mahalle"
                                ng-options="mahalle.kod as mahalle.ad for mahalle in mahalleler"
                                required>
                            <option value="" selected>Seçiniz..</option>
                            <option value="">{{mahalle.ad}}</option>
                        </select>
                        <div class="alert alert-danger alert-dismissable"
                             ng-show="form_ilan.mahalle.$dirty && form_ilan.mahalle.$invalid">
                            <span ng-bind="hataGoster({'tur':form_ilan.mahalle.$error})"></span>
                        </div>
                    </div>
                </div>
                <div class="row form-group" ng-show="ilan.mahalle > 0">
                    <div class="col-lg-2 col-lg-push-2 form-control-static">
                        Adres:
                    </div>
                    <div class="col-lg-6 col-lg-push-2">
                        <input type="text" class="form-control"
                               ng-minlength=10
                               ng-maxlength=200
                               name="adres"
                               ng-model="ilan.adres"
                               required/>
                        <div class="alert alert-danger alert-dismissable"
                             ng-show="form_ilan.adres.$dirty && form_ilan.adres.$invalid">
                            <span ng-bind="hataGoster({'tur':form_ilan.adres.$error, 'uzunluk': {min:10, max:200}})"></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="text-right">
            <input type="submit" class="btn btn-primary" ng-disabled="form_ilan.$invalid" value="Kaydet"/>
            <input type="button" class="btn btn-danger" value="Vazgeç" ng-click="vazgec()"/>
        </div>
    </form>
</div>